name = "anivora"
pages_build_output_dir = "./"
compatibility_date = "2025-01-01"

[[d1_databases]]
binding = "DB"
database_name = "anivora-db"
database_id = "6d1d8027-bb61-40f8-84b9-f07885b0291a"